version: '3.1'

services:

  nats-streaming:
    image: nats-streaming:0.21.1-alpine3.13
#    container_name: nats-streaming
    ports:
      - "14222:4222"
      - "18222:8222"
      - "16222:6222"
    command:
      - "--cluster_id=nats-streaming"
      - "--user=user"
      - "--pass=pass"
      - "--store=file"
      - "--dir=datastore"
#    volumes:
#      - nats:/datastore
    restart: unless-stopped

  postgress:
    image: postgres:latest
#    container_name: postgress
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      # PGDATA: /data/postgres
    volumes:
      # - /data/postgres:/data/postgres
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

#  scyllasb:
#    image: scylladb/scylla:latest
##    container_name: scylladb
#    expose:
#      - "9042"
#      - "9142"
#    ports:
#      - "9042:9042"
#      - "9142:9142"
#      - "9160:9160"
#      - "10000:10000"
#    volumes:
#      - scylla:/var/lib/scylla
#    command: "--smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0"
#    restart: unless-stopped

volumes:
  nats:
  scylla:

